import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {ShopStore,walletFor,loadCatalog} from '../shop/store.mjs';
import {SocialStore,socialInput} from '../social/store.mjs';
import {activeRoundId} from '../slack/invitations.mjs';
const url=process.env.TEST_CHAT_REDIS_URL;
const key=s=>createHash('sha256').update(s).digest('hex');
test('social input refuses self gifts, fractional amounts and empty messages',()=>{
 const body={id:randomUUID(),kind:'donut',amount:1};
 assert.throws(()=>socialInput(body,{self:'a',peer:'a'}),/choose_a_neighbor/);
 for(const amount of [0,-1,1.2,1000,'5'])assert.throws(()=>socialInput({...body,amount},{self:'a',peer:'b'}),/invalid_amount/);
 assert.throws(()=>socialInput({...body,kind:'note',text:' '},{self:'a',peer:'b'}),/invalid_message/);
});
test('real Redis: shared pairing, gifts, purchases and private threads survive retries',{skip:!url},async()=>{
 assert(['127.0.0.1','localhost'].includes(new URL(url).hostname));
 const namespace='CTEST'+randomUUID().replaceAll('-','').toUpperCase();
 const shop=new ShopStore({url,token:'local-test',key:namespace+':wallet'}),social=new SocialStore(shop,namespace),catalog=loadCatalog();
 const a=key(namespace+'a'),b=key(namespace+'b'),c=key(namespace+'c');
 const round=activeRoundId();
 const invite={id:randomUUID(),inviterId:'UA',inviteeId:'UB',inviterName:'A',priority:1,status:'pending',createdAt:new Date().toISOString()};
 await social.invitation('add',invite,round);
 await assert.rejects(()=>social.invitation('answer',{id:invite.id,inviter:'UA',responder:'UC',status:'accepted'},round,[a,c]),/invitation_not_active/);
 await Promise.all(Array.from({length:12},()=>social.invitation('answer',{id:invite.id,inviter:'UA',responder:'UB',status:'accepted'},round,[a,b])));
 assert.equal(walletFor({purse:await shop.purse(a,catalog)}).balance,5);
 assert.equal(walletFor({purse:await shop.purse(b,catalog)}).balance,5);
 await assert.rejects(()=>social.invitation('add',{...invite,id:randomUUID(),inviteeId:'UC'},round),/already_booked/);
 const gift=socialInput({id:randomUUID(),kind:'donut',amount:3},{self:a,peer:c});
 await Promise.all(Array.from({length:10},()=>social.event(gift)));
 assert.equal(walletFor({purse:await shop.purse(a,catalog)}).balance,2);
 assert.equal(walletFor({purse:await shop.purse(c,catalog)}).balance,3);
 await assert.rejects(()=>social.event({...gift,amount:1}),/request_conflict/);
 const item={id:'deco-rug',price:2};
 const race=await Promise.allSettled([shop.buy(a,item,{},0),social.event({...gift,id:randomUUID(),amount:2})]);
 assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
 assert.equal(walletFor({purse:await shop.purse(a,catalog)}).balance,0);
 const note=socialInput({id:randomUUID(),kind:'note',text:'<script>not markup</script>'},{self:b,peer:c});
 await social.event(note);
 await social.visit(c,b);
 assert.equal((await social.home(c)).notes[0].text,note.text);
 assert.equal((await social.home(c)).visitors[0].from,b);
 const dm=socialInput({id:randomUUID(),text:'Hello privately'},{self:b,peer:c,messaging:true});
 await social.event(dm);
 assert.equal((await social.messages(c,b))[0].text,dm.text);
 assert.deepEqual(await social.messages(a,b),[]);
 assert.equal((await social.messages(c))[0].from,b);
 const reaction=socialInput({id:randomUUID(),kind:'flower'},{self:b,peer:c});
 await social.event(reaction);
 await assert.rejects(()=>social.event({...reaction,id:randomUUID()}),/try_again_later/);
});
